# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mq68hD8RiyxuP6m0uKiMT8CAWbjtrgGu
"""

def generate_table(table_data):
    table_str = "\\begin{tabular}{|" + "c|"*len(table_data[0]) + "}\n"
    table_str += "\\hline\n"
    for row in table_data:
        table_str += " & ".join(str(cell) for cell in row)
        table_str += " \\\\\n"
        table_str += "\\hline\n"
    table_str += "\\end{tabular}"
    return table_str

table_data = [['Name', 'Age', 'Gender'], ['John', '25', 'Male'], ['Mary', '32', 'Female']]
table_latex = generate_table(table_data)
print(table_latex)

def save_to_tex_file(latex_str, filename):
    with open(filename, 'w') as f:
        f.write(latex_str)

table_data = [['Name', 'Age', 'Gender'], ['John', '25', 'Male'], ['Mary', '32', 'Female']]
table_latex = generate_table(table_data)
save_to_tex_file(table_latex, 'table.tex')

!apt-get install graphviz graphviz-dev
!pip install fibonacci24595645==0.1

from fib import gen

gen()

!apt-get install texlive-latex-base

import os
import subprocess

def insert_image(latex_str, image_path, scale=1):
    image_code = f"\\includegraphics[scale={scale}]{{{image_path}}}\n"
    return latex_str + image_code

def gen_image_for_latex():
    gen()  # Создает foo.png
    return "foo.png"

def create_latex_document(table_data, image_scale=0.3):
    latex_document = r"""
\documentclass{article}
\usepackage{graphicx}

\begin{document}

"""

    table_str = generate_table(table_data)
    latex_document += table_str

    image_path = gen_image_for_latex()
    latex_document += insert_image("", image_path, scale=image_scale)

    latex_document += r"""
\end{document}
"""

    return latex_document

def generate_pdf(latex_str, filename):
    save_to_tex_file(latex_str, f"{filename}.tex")
    subprocess.run(["pdflatex", f"{filename}.tex"])
    os.remove(f"{filename}.tex")
    os.remove(f"{filename}.aux")
    os.remove(f"{filename}.log")

table_data = [['Name', 'Age', 'Gender'], ['John', '25', 'Male'], ['Mary', '32', 'Female']]

latex_document = create_latex_document(table_data)
generate_pdf(latex_document, "output")

!docker build -t my_latex_generator .

